feature: Добавлена форма на отзывы + заполненность в зависимости от п…
WhyLesS/Reactives pull request #3
Opened 2024-07-08 14:51 UTC by WhyLesS

feature: Добавлена форма на отзывы + заполненность в зависимости от положения на странице.

2024-07-08 18:17 UTC, zubkov7 commented on src/components/App.jsx
> +    const [scrollProgress, setScrollProgress] = useState(0);
давайте вынесем ProgressBar в отдельный компонент. В текущей реализации на скролл происходит ререндер всего приложения

2024-07-08 18:19 UTC, zubkov7 commented on src/hooks/useCounters.jsx
> +export const useCounters = (itemsNumber) => {
сейчас уже нет необходимости возвращать массив, давайте перепишем на один каунтер

2024-07-08 18:21 UTC, zubkov7 requested changes

2024-07-08 18:21 UTC, zubkov7 commented on src/components/App.jsx
> +            <div className="bar" style={{ width: `${scrollProgress}%` }}></div>
давайте вынесем ProgressBar в отдельный компонент. В текущей реализации на скролл происходит ререндер всего приложения

2024-07-10 12:08 UTC, zubkov7 commented on src/hooks/useCounters.jsx
> +export const useCounters = (itemsNumber) => {
этот файл еще используется? если нет, то предлагаю удалить и замержить ))

2024-07-10 12:18 UTC, WhyLesS commented on src/hooks/useCounters.jsx
> +export const useCounters = (itemsNumber) => {
а, да, удалю

2024-07-10 12:35 UTC, merged